language: node_js
sudo: false
node_js:
    - "7"
before_script:
    - npm install -g npm
    - npm install -g grunt-cli
script:
    - "npm test"
notifications:
    irc:
        channels:
            - "ircs://irc.barafranca.com:6679#dev"
        template:
            - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
            - "Build details : %{build_url}"
        skip_join: true
